Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
GC : real
F : REAL



Inicio
ESCREVA("GRAUS CELCIUS : ")
LEIA(GC)


F:= (9 * GC) + 160) / 5


ESCREVAL("GRAUS EM FAHRNHEIT É : ", F  )


Fimalgoritmo