Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
AREA,RAIO: real



Inicio
ESCREVAL("ESCREVA O RAIO DA CIRCUFERENCIA")
LEIA(RAIO)

AREA:= 3,14 * (RAIO * RAIO)

ESCREVAL("A AREA DA CIRCUFERENCIA É : ", AREA )


Fimalgoritmo