Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
RAIO, ALTURA: REAL
VOLUME, V1, R: REAL



Inicio
ESCREVA("ESCREVA RAIO : ")
LEIA(RAIO)
ESCREVA (" ESCREVA ALTURA : ")
LEIA(ALTURA)

R:= RAIO * RAIO
V1:= 3,14 * R
VOLUME:= V1 * ALTURA


ESCREVAL("O RESULTADO DO VOLUME É : ", VOLUME )


Fimalgoritmo