Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
NUMERO1, NUMERO2, SOMA: real



Inicio
ESCREVA("ESCREVA UM NUMERO : ")
LEIA(NUMERO1)
ESCREVA("ESCREVA OUTRO NUMERO: ")
LEIA(NUMERO2)


SOMA:=(NUMERO1 + NUMERO2)

ESCREVAL("O RESULADO É : ", SOMA)


Fimalgoritmo