Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
AREA,BASE, ALTURA: real



Inicio
ESCREVAL("ESCREVA A BASE DO TRIANGULO")
LEIA(BASE)
ESCREVAL ("ESCREVA A ALTURA DO TRIANGULO")
LEIA(ALTURA)


AREA:=(BASE*ALTURA)/2

ESCREVAL("A AREA DO TRIANGULO É : ", AREA )


Fimalgoritmo