Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
FH : INTEIRO
C, C2, C3 : REAL



Inicio
ESCREVA("GRAUS FAHRNHEIT : ")
LEIA(FH)


C:= FH – 32
C2:= 5/9
C3:= C * C2


ESCREVAL("GRAUS EM CELCIUS É : ", C3  )


Fimalgoritmo